# Generated by Django 3.1.2 on 2020-11-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
