# Generated by Django 3.1.2 on 2020-11-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_system', '0003_auto_20201116_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
