# Generated by Django 3.1.2 on 2020-11-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_system', '0004_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='motto',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
