# Generated by Django 3.1.2 on 2020-11-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_system', '0005_auto_20201117_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='motto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
