# Generated by Django 3.1.2 on 2020-11-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_system', '0006_auto_20201117_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
